### ISSUE TITLE
ЛОР: Есть несколько неприятных проблем

### ISSUE THREAD

**Issue by zvezdochiot** [OpenA/lorify-ng#3]
Есть несколько неприятных проблем:

https://www.linux.org.ru/forum/lor-source/13898862?cid=15035489

**Comment by zvezdochiot** [comment]
есть очень неприятный баг в версии для ФФ.

https://www.linux.org.ru/forum/lor-source/13898862?cid=15036025

**Comment by OpenA** [comment]
Хорошо, с дачи приеду починю накопленое

**Comment by zvezdochiot** [comment]
Пофиксено в 2.7.3. Спасибо. :)
