### ISSUE TITLE
Скрипт ломается при отключённых оповещениях

### ISSUE THREAD

**Issue by ddvarpdd** [OpenA/lorify-ng#4]
В Firefox имеется возможность полностью выключить функционал оповещений, переключив настройку dom.webnotifications.enabled на false в about:config. В этом случае скрипт не может инициализироваться, останавливаясь на проверке Notification.permission, поскольку при такой настройке Notification is not defined. Разумно было бы обернуть соответствующий switch в условие проверки того, определён ли этот самый Notification.

**Comment by OpenA** [comment]
Добавил проверку в версии **v2.9.1**
