### ISSUE TITLE
Не работают уведомления

### ISSUE THREAD

**Issue by eternal-sorrow** [OpenA/lorify-ng#6]
У меня последнее время не работают уведомления. Они как бы всегда работали не очень стабильно и надёжно. Иногда требовалось перезапустить браузер, чтобы уведомления опять заработали. А с какого то момента перестали работать совсем. Не имею понятия, как отдебажить их.

**Comment by yurikoles** [comment]
А инфа про браузер, систему?

**Comment by eternal-sorrow** [comment]
Firefox 73, linux. Использую расширение, не юзерскрипт.

**Comment by OpenA** [comment]
Должно быть поправлено в версии 2.9.6

**Comment by eternal-sorrow** [comment]
Не исправлено. Уведомление появляется только когда я захожу на сайт, то есть когда оно бксполезно.
