### ISSUE TITLE
Цитировать только выделенный текст при `Ответить с цитатой`

### ISSUE THREAD

**Issue by icher** [OpenA/lorify-ng#7]
Иногда комментарий слишком большой и лишний оверквотинг совсем ни к чему. Хотелось бы, чтобы функция `Ответить с цитатой` цитировала только выделенный текст, а не все сообщение.

**Comment by OpenA** [comment]
Такая функция есть при выделении любого текста на экране и нажатия кнопки `quote` или `>` или аналогичной стрелки на клавиатуре через `shift`+`.`

Функция "Ответить с цитированием" запиливалась ради того что бы извлечь исходную разметку цитируемого поста и заключить в цитату. Сейчсас это реализовано путем обратного парсинга html потому что на лоре нет функции позволяющей левому юзеру получить исходник чужого поста.

Но в принципе нет проблем сделать цитату умнее и не весь текст копипастить а как то разрезать на цитаты с отступом что ли. Еще в настройки добавить опцию игнора блоков кода, включенных цитат и тому подобного.
