### ISSUE TITLE
Не удаётся загрузить распакованное расширение

### ISSUE THREAD

**Issue by KOT040188** [OpenA/lorify-ng#8]
Пытаюсь загрузить распакованное расширение и вылазит такая ошибка:
Ошибка загрузки расширения
Файл
~/bin/ext/lorify-ng-master
Ошибка
Could not load icon 'icons/loriko-64.png' specified in 'browser_action'.
Не удалось загрузить манифест.

**Comment by OpenA** [comment]
Возьми вот отсюда [loriko-64.png](https://addons.mozilla.org/user-media/addon_icons/907/907832-64.png?modified=64f7388d) и кинь в папку icons

Расширения векторные картинки не поддерживают просто, а держать блобы в репозитории с исходниками дурной тон.

**Comment by yurikoles** [comment]
> держать блобы в репозитории с исходниками дурной тон.

`git lfs`?

**Comment by OpenA** [comment]
Ну как бы в папке лежит **loriko.svg** (исходник иконки), сохранить его в png в эту же папку нет никакой проблемы.  
Это один момент. Второй - может кто-то захочет старую иконку или эту, но к примеру с другими цветами подходящими для своей оконной темы - пожалуйста и ее не будет перезатирать при обновлении кода (в гитигнор правило для png добавлены).

Но я не знал что хром совсем отказывается расширение грузить без картинки.

**Comment by KOT040188** [comment]
Теперь загрузило, но всё равно показывает ошибки https://imgur.com/xai9s8g

**Comment by OpenA** [comment]
Это предупреждение о том что к 2023 поддержку манефеста v2 прекратят.
Обновлю к тому времени.

**Comment by OpenA** [comment]
исправлено в v3.2.2
